myfb/login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.connect, name='connect'),
    path('create_account', views.create, name='create'),
    path('connexion', views.connexion, name ='connexion'),
    path('logout',views.logout_view, name = 'logout'),
    path('creation', views.creation, name='creation'),
    path('modification/<str:user>', views.modif, name= 'modif'),
    path('enregistrer/<str:user>', views.enreg, name = 'enregistrer')
]

myfb/myfb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]

myfb/login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

myfb/login/views.py
from .models import User
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404,render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse

def connect(request):
    return render(request, 'login/connect.html', {})

def create(request):
    return render(request, 'login/create.html', {})

def connexion(request):
    username = request.GET['name']
    password = request.GET['password']
    user = authenticate(username=username, password=password)
    if user is not None:
    # A backend authenticated the credentials
        login(request, user)
        return render(request, 'login/account.html', {
            'user':user,
        })
    else:
    # No backend authenticated the credentials
        return render(request, 'login/connect.html', {
            'error_message': "Nom d'utilisateur ou Mot de Passe incorrect",
        })

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('login:connect'))

def creation(request):
    use = request.POST['name']
    try:
        man = User.objects.get(username=use)
    except:
        first = request.POST['first']
        last = request.POST['last']
        mail = request.POST['mail']
        passw = request.POST['password']
        user = User.objects.create_user(username=use,password=passw,email=mail, first_name = first, last_name= last)
        login(request, user)
        return render(request, 'login/account.html', {
            'user':user,
        })
    return render(request, 'login/create.html', {
        'error_message':"Nom d'utilisateur déjà utilisé !"
    })

from django.contrib.auth.decorators import login_required

#@login_required
def modif(request, user):
    utilisateur=request.user
    return render(request, 'login/modif.html', {user:utilisateur})

#@login_required
def enreg(request, user):
    utilisateur = request.user
    mail = request.POST['mail']
    utilisateur.email = mail
    utilisateur.save()
    return render(request, 'login/account.html', {user:utilisateur})

myfb/login/templates/login/account.html
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Mon Compte</title>
</head>

<h1>Salut {{user.first_name}} !</h1>

<ul>
    <li>Prénom : {{user.first_name}}</li>
    <li>Nom : {{user.last_name}}</li>
    <li>user_name : {{user.username}}</li>
    <li>mail : {{user.email}}</li>
</ul>

<a href={% url 'login:modif' user.username %}>Modifier</a><br>

<a href={% url 'login:logout' %}>Déconnexion</a>

myfb/login/templates/login/connect.html

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Login</title>
    {% load bootstrap4 %}
</head>


<h1>Page de Connexion :</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'login:connexion' %}" method="get" id='form'>
    
    <label for="name">Nom d'utilisateur : </label>
    <input type="text" id="name" name="name" required placeholder = "nom_utilisateur" > <br>
    <label for="password">Mot de Passe : </label>
    <input type="password" id="password" name="password" required placeholder = "mot_de_passe" > <br>
    <input type="submit" value="Se connecter">
</form>


<a href={% url 'login:create' %}>Créer un compte</a>

myfb/login/templates/login/create.html
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Créer un compte</title>
</head>
    
<h1>Créer un compte :</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'login:creation' %}" method="post">
    {% csrf_token %}
    <label for="name">Nom d'utilisateur : </label>
    <input type="text" id="name" name="name" required > <br>
    <label for="name">Prénom : </label>
    <input type="text" id="first" name="first" required > <br>
    <label for="name">Nom : </label>
    <input type="text" id="last" name="last" required > <br>
    <label for="mail">Adresse e-Mail : </label>
    <input type="text" id="mail" name="mail" required> <br>
    <label for="password">Mot de Passe : </label>
    <input type="password" id="password" name="password" required> <br>
    <input type="submit" value="Créer">
</form>


<a href={% url 'login:connect' %}>retour</a>

myfb/login/templates/login/modif.html
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Modification</title>
</head>


<h1>Modifiez votre email {{user.first_name}}</h1>

<form action="{% url 'login:enregistrer' user.username%}" method="post">
    {% csrf_token %}
    <label for="name">Nouveau Mail : </label>
    <input type="text" id="mail" name="mail" required value = "" > <br>
    <input type="submit" value="Enregistrer">
</form>